### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#3]
I'm sorry to open another issue so soon after the last but I was wondering how the nginx config works, I'm trying to make it work with my domain, replaced localhost with my domain name and kept the subdomains there, but it's not loading up, even through direct IP. I was just wondering how you set it up since I'm unable to get it working

**Comment by lwatsondev** [comment]
Post your config.

**Comment by camjac251** [comment]
I think I figured it out, config was enabled for local only at first and I didn't quite understand what each server block was for. I noticed it had php7 as its socket, is that recommended? I'm only running 5.5

**Comment by lwatsondev** [comment]
I develop and test on PHP 7, so there's no guarantee it'll work on lower versions, but I'm fairly sure I don't do anything that would stop it, so give it a try.

**Comment by camjac251** [comment]
I decided to just upgrade since it seems like it's recommended. With your install, do you have all of the storage on one server? It'd be good to add slave nodes as storage or integrate cloud storage like S3, Amazon Cloud Drive, etc.

**Comment by lwatsondev** [comment]
In theory it should just support various cloud storage services provided
you configure config/storage.php, and have the appropriate dependencies
installed. Serving remote files through the application should also
work provided you're using x-accel or x-sendfile, since after the
request hits PHP, it does it's checks and then offloads sending the
actual file to your webserver, meaning you could just use proxy_pass [1]
or equivalent to retrieve the file from the remote location within the
/upload/ location block.

[1] http://nginx.org/en/docs/http/ngx_http_proxy_module.html

**Comment by camjac251** [comment]
Do you mean [config/filesystems.php](https://laravel.com/docs/5.2/filesystem) instead of config/storage.php? storage.php has no mention in the official laravel docs but filesystem does. By changing the `'default' => 'local',`, would that change where the storage folder goes?
