### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by camjac251** [TheReverend403/uPste#35]
Would it be possible to support PHP 7.2? With 7.1 (max supported php version by Laravel 5.2) ending its active support on the first of next month and ending security updates a year from now it might be risky to keep running 7.1.

Laravel 5.4 is the next version to support 7.2 it seems according to this, [5.3 requirements](https://laravel.com/docs/5.3) [5.4 requirements](https://laravel.com/docs/5.4)

[Link to dates of PHP EOLs](https://secure.php.net/supported-versions.php)

**Comment by lwatsondev** [comment]
Even though it doesn't *officially* support 7.2, I am running https://pste.pw on 7.2 with no problems. Your error at #36 is not because of PHP versions. I suspect what has happened is you've switched php versions but not given the new php-fpm write access to that folder.

This repo is no longer actively developed anyway. I'm working on a rewrite at https://github.com/FoxDev/pste.

**Comment by camjac251** [comment]
Oh I was unaware of a rewrite. This is very exciting.

Would it be possible for the rewrite to be able to migrate over a current install of uPste for the new system when it is ready for production?
